# Cấu hình Database PostgreSQL
spring.datasource.url=jdbc:postgresql://[GIÁ_TRỊ_PGHOST_TỪ_RAILWAY]:5432/railway
spring.datasource.username=postgres
spring.datasource.password=[GIÁ_TRỊ_PGPASSWORD_TỪ_RAILWAY]
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate (Tự động tạo bảng)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Cấu hình upload file
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cấu hình port
server.port=${PORT:8080}